document.write( '<!DOCTYPE html>\n' );
document.write( '<html>\n' );
document.write( '<body>\n' );
document.write( '<title> ANSIBLE DEMO </title>\n' );
document.write( '<body style=\"background-color:white;\">\n' );
document.write( ' <img src=\"C:UsersuserDownloadssysmedac.png\"  width=\"400\" height=\"200\">\n' );
document.write( '\n' );
document.write( ' \n' );
document.write( '\n' );
document.write( '<h1 style=\"text-align:center;\"> DEMO PROJECT </h1>\n' );
document.write( '<h2 style=\"text-align:center\"> ANSIBLE-DEMO </h2>\n' );
document.write( '<p style=\"text-align:center\">  Ansible in Ubuntu deploying with Jenkins </p>\n' );
document.write( '<p style=\"text-align:center\"> Date/Time: <span id=\"datetime\"></span></p>\n' );
document.write( '<script>\n' );
document.write( 'var dt = new Date();\n' );
document.write( 'document.getElementById(\"datetime\").innerHTML = dt.toLocaleString();\n' );
document.write( '</script>\n' );
document.write( '</body>\n' );
document.write( '</html>' );
